server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
    username: root
    password: test@123
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

# The SQL dialect makes Hibernate generate better SQL for the chosen database


